export const data = [
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-73-scaled-2550x1912.jpg",
        title:"Kvadratchalar",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-72-scaled-2550x1912.jpg",
        title:"Ikat",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-71-scaled-2550x1912.jpg",
        title:"Davralar",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-70-scaled-2550x1912.jpg",
        title:"Geometriya ko'k",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-69-1-scaled-2550x1912.jpg",
        title:"Tropik barglar",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-68-scaled-2550x1912.jpg",
        title:"Bambi",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-67-scaled-2550x1912.jpg",
        title:"Vizantiya",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-66-scaled-2550x1912.jpg",
        title:"Kechki bog'",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg9-DP-likxW.jpg",
        title:"Pat markiz",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://www.bnpfabric.uz/wp-content/uploads/2024/02/diz-64-scaled-2550x1912.jpg",
        title:"Lavanda Atirgullari",
        category:"Qish kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg11-4aXKsJZC.jpg",
        title:"Safari",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg12-DxA5ccVB.jpg",
        title:"Ko'p rangli ametist",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg13-LbBmrKZ2.jpg",
        title:"Shivali bizak",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg14-DDwESftW.jpg",
        title:"Zumrad AB",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg15-Bu3C84nj.jpg",
        title:"Malahit qutisi",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg16-CrmeMFF3.jpg",
        title:"Bahorning hidlari",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg18-DuuQsd8S.jpg",
        title:"Moviy Shabada",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg19-p6tq_Bf2.jpg",
        title:"Moviy suv",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg20-CerQyIaR.jpg",
        title:"Plaid",
        category:"Kuz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },


    {
        img:"https://bnpfabri.vercel.app/assets/productImg21-C-p6aOaW.jpg",
        title:"Vintage uslubi",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg22-emL6vfU-.jpg",
        title:"Tebraniyotgan Karahindiba",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg23-CL7pBMvF.jpg",
        title:"Fransuz Riviera",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg24-B1gnyX0U.jpg",
        title:"Qo'y dolli",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg25-BvXKeYJI.jpg",
        title:"Alp tog'lari o'simliklari",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg26--z9MeTTg.jpg",
        title:"Ilhomlantiruvchi",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg27-DsTk7fxd.jpg",
        title:"Yashil lotus",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg28-DaHXHjbW.jpg",
        title:"Tog'li makkajo'xori",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg29-UBLglkL9.jpg",
        title:"Sakura",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },
    {
        img:"https://bnpfabri.vercel.app/assets/productImg30-DXgEC2ST.jpg",
        title:"Zaytun novdasi",
        category:"Yoz kolleksiyasi",
        material:"Paxta Flanel",
        company:"Buxoro tabiiy mahsuloti",
    },



];
export default data;